version: '2'
services:
    kasa-app:
        image: kasa
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://kasa-mysql:3306/kasa?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kasa-mysql:
        extends:
            file: mysql.yml
            service: kasa-mysql
